# Funding options for the project
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (recommended)
github: [wildcard]

# Patreon
# patreon: username

# Open Collective
# open_collective: cmdai

# Ko-fi
# ko_fi: username

# Buy Me a Coffee
# buy_me_a_coffee: username

# Custom sponsorship links (up to 4)
# custom:
#   - https://example.com/sponsor
