# Release Drafter Configuration
# Automatically drafts release notes based on merged PRs
#
# PRs are organized by MODULE first (monorepo structure), then by change type.
# The Rust CLI is the main product and appears first in release notes.

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  # =============================================================================
  # RUST CLI (Main Product) - Changes to the core CLI binary
  # Paths: src/**, Cargo.toml, Cargo.lock, build.rs, tests/**, benches/**
  # =============================================================================
  - title: ':crab: Caro CLI'
    labels:
      - 'module:cli'

  # =============================================================================
  # AUXILIARY MODULES - Supporting projects in the monorepo
  # =============================================================================
  - title: ':globe_with_meridians: Website'
    labels:
      - 'module:website'

  - title: ':books: Documentation Site'
    labels:
      - 'module:docs-site'

  - title: ':open_file_folder: Documentation'
    labels:
      - 'module:docs'

  - title: ':speaking_head: Caro Voice'
    labels:
      - 'module:voice'

  - title: ':package: npm Package'
    labels:
      - 'module:npm'

  - title: ':package: NuGet Package'
    labels:
      - 'module:nuget'

  - title: ':desktop_computer: Apps & DevRel'
    labels:
      - 'module:apps'

  - title: ':art: Landing Page'
    labels:
      - 'module:landing'

  # =============================================================================
  # INFRASTRUCTURE - CI/CD, tooling, and project-wide changes
  # =============================================================================
  - title: ':gear: CI/CD & Infrastructure'
    labels:
      - 'module:ci'
      - 'ci/cd'

  # =============================================================================
  # CHANGE TYPE CATEGORIES - For PRs not matching specific modules
  # =============================================================================
  - title: ':boom: Breaking Changes'
    labels:
      - 'breaking-change'

  - title: ':rocket: Features'
    labels:
      - 'enhancement'

  - title: ':bug: Bug Fixes'
    labels:
      - 'bug'

  - title: ':shield: Security'
    labels:
      - 'security'

  - title: ':zap: Performance'
    labels:
      - 'performance'

  - title: ':wrench: Maintenance'
    labels:
      - 'dependencies'
      - 'testing'

  - title: ':package: Other Changes'
    labels:
      - '*'

# Exclude certain labels from release notes
exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'invalid'
  - 'wontfix'
  - 'stale'

# =============================================================================
# AUTO-LABELING RULES
# Module labels are applied based on file paths to categorize PRs by project.
# The Rust CLI (module:cli) is the main product.
# =============================================================================

autolabeler:
  # ---------------------------------------------------------------------------
  # MODULE LABELS - Based on file paths in the monorepo
  # ---------------------------------------------------------------------------

  # Rust CLI (Main Product) - Core binary and library code
  - label: 'module:cli'
    files:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.rs'
      - 'tests/**'
      - 'benches/**'
      - 'clippy.toml'
      - 'rustfmt.toml'
      - 'deny.toml'

  # Website - Marketing and product website
  - label: 'module:website'
    files:
      - 'website/**'

  # Documentation Site - Technical documentation (Astro-based)
  - label: 'module:docs-site'
    files:
      - 'docs-site/**'

  # Documentation - Markdown docs in docs/ folder
  - label: 'module:docs'
    files:
      - 'docs/**'

  # Caro Voice - Voice/speech integration
  - label: 'module:voice'
    files:
      - 'caro-voice/**'

  # npm Package - Node.js distribution
  - label: 'module:npm'
    files:
      - 'npm/**'

  # NuGet Package - .NET distribution
  - label: 'module:nuget'
    files:
      - 'nuget/**'

  # Apps & DevRel - Developer relations and apps
  - label: 'module:apps'
    files:
      - 'apps/**'

  # Landing Page
  - label: 'module:landing'
    files:
      - 'landing/**'

  # CI/CD & Infrastructure
  - label: 'module:ci'
    files:
      - '.github/**'

  # ---------------------------------------------------------------------------
  # CHANGE TYPE LABELS - Based on branch names and PR titles
  # ---------------------------------------------------------------------------

  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/fix/i'
      - '/bug/i'

  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/feat/i'
      - '/feature/i'
      - '/add/i'

  - label: 'documentation'
    branch:
      - '/docs\/.+/'
    title:
      - '/docs/i'
      - '/documentation/i'

  - label: 'ci/cd'
    branch:
      - '/ci\/.+/'
      - '/github-actions\/.+/'

  - label: 'dependencies'
    branch:
      - '/deps\/.+/'
      - '/dependabot\/.+/'

  - label: 'testing'
    branch:
      - '/test\/.+/'

  # ---------------------------------------------------------------------------
  # COMPONENT LABELS - Specific areas within the CLI
  # ---------------------------------------------------------------------------

  - label: 'backend'
    files:
      - 'src/backends/**'

  - label: 'safety'
    files:
      - 'src/safety/**'

# Version resolver based on labels
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'documentation'
      - 'ci/cd'
      - 'dependencies'
      - 'performance'
  default: patch

# Template for release notes
# PRs are organized by module (Rust CLI first, then auxiliaries)
template: |
  ## What's Changed

  $CHANGES

  ---

  ## Contributors

  $CONTRIBUTORS

  ---

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Installation

  ```bash
  # Using cargo (recommended)
  cargo install caro

  # Using the install script
  curl -fsSL https://caro.sh/install | sh

  # Or download the binary for your platform from the assets below
  ```

# Change template for each PR
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

# Template for changes without a category
change-title-escapes: '\<*_&'

# Sorting PRs
sort-by: merged_at
sort-direction: descending

# Replacers for consistent formatting
replacers:
  - search: '/\[skip ci\]/g'
    replace: ''
  - search: '/\[ci skip\]/g'
    replace: ''
