Feature: Community Engagement Agent Workflows
  As a CARO community operator
  I want automated engagement workflows
  So that high-value contributors are recognized and retained

  Background:
    Given the Hub API is available
    And community engagement config is loaded from community_engagement.yaml
    And the current autonomy phase is "Phase 1" (approval required)

  # --- Daily Engagement Cycle ---

  Scenario: Daily engagement run identifies top contributors
    Given the @insight-agent has fresh data from the Hub API
    When the daily engagement cycle runs
    Then the @scoring-agent computes scores for all active contributors
    And the top 5 contributors by daily score delta are identified
    And any milestone crossers from the last 24h are identified
    And the total outreach targets do not exceed 10

  Scenario: Daily run skips recently contacted users
    Given user "brave-ocean-tiger" was contacted 2 days ago
    When the daily engagement cycle selects outreach targets
    Then "brave-ocean-tiger" is excluded from this cycle
    Because the minimum gap between contacts is 3 days

  Scenario: Daily run produces drafts, not sent messages
    Given the daily engagement cycle has identified 7 outreach targets
    When drafts are generated by @outreach-agent
    Then 7 drafts are added to the engagement queue
    And each draft has status "pending_approval"
    And no messages are sent without human approval

  # --- Personalized Outreach ---

  Scenario: Outreach draft references specific user contributions
    Given user "calm-river-stone" created recipe "convert-video-to-mp4"
    And the recipe has been run 47 times by 12 distinct users
    When @outreach-agent drafts a Recognition message
    Then the CLI version references "convert-video-to-mp4" by name
    And the CLI version includes the number "47" or "12"
    And the draft passes the specificity check

  Scenario: Generic outreach is rejected
    Given user "swift-mountain-hawk" has a score of 15
    But no individual recipe has been reused by others
    When @outreach-agent attempts to draft a message
    Then the draft is rejected
    Because it cannot reference a specific impactful action

  Scenario: Outreach complies with persona voice constraints
    Given @outreach-agent drafts a message for any user
    Then the message does not contain "Thanks for contributing!"
    And the message does not contain "amazing" or "incredible"
    And the message does not contain "unlock" or "premium"
    And the message does not contain "earn income" or "tradable"

  # --- Channel Selection ---

  Scenario: Channel selection prefers CLI for active terminal users
    Given user "bold-forest-elk" is active in the CLI
    And their CLI message count this week is 0
    When @channel-agent selects a channel for a Recognition message
    Then the primary channel is "cli"

  Scenario: Channel selection respects frequency limits
    Given user "bold-forest-elk" received 2 CLI messages this week
    When @channel-agent selects a channel for a Recognition message
    Then the primary channel is NOT "cli"
    And the primary channel is "web" (badge)

  Scenario: Founder invitations always use email
    Given user "deep-crystal-wave" qualifies for Founder tier
    And they have an email address on file
    When @channel-agent selects a channel for an Invitation
    Then the primary channel is "email"

  Scenario: Multi-channel for major milestones
    Given user "bright-coral-sun" hit 1000 total recipe runs
    When @channel-agent evaluates the milestone
    Then multi_channel is true
    And channels include "email" and "web"

  # --- Contribution Scoring ---

  Scenario: Scoring formula weights reuse over creation
    Given user A created 50 recipes with 0 reuses
    And user B created 5 recipes with 20 reuses each
    When @scoring-agent computes scores
    Then user B scores higher than user A
    Because reuse weight (3) exceeds creation weight (1)

  Scenario: Gaming detection flags suspicious patterns
    Given user "rapid-spark-fox" created 30 recipes in 24 hours
    And only 1 of those recipes has been reused
    When @scoring-agent evaluates their activity
    Then the gaming_suspect flag is set to true
    And they are excluded from outreach targeting

  Scenario: Score decay favors recent contributions
    Given user "old-stone-wall" had 100 reuses 60 days ago
    And user "new-river-flow" had 50 reuses today
    When @scoring-agent computes decayed scores
    Then "new-river-flow" ranks higher than "old-stone-wall"
    Because decay_factor at 60 days is 0.25

  # --- Founder Tier ---

  Scenario: Founder invitation triggered after sustained high score
    Given user "wise-cedar-root" has decayed_score of 250
    And they have been active for 45 days
    And they have no gaming flags
    When @founder-agent evaluates candidates
    Then "wise-cedar-root" is marked as eligible
    And an invitation draft is created
    And the draft requires human approval

  Scenario: Founder invitation references specific contributions
    Given user "wise-cedar-root" is a Founder candidate
    And their top recipe "batch-pdf-merge" has 200 runs
    When @founder-agent drafts an invitation
    Then the invitation body references "batch-pdf-merge"
    And it mentions the 200 run count

  Scenario: Declined invitations respect cooldown
    Given user "quiet-lake-mist" declined a Founder invitation 30 days ago
    When @founder-agent evaluates candidates
    Then "quiet-lake-mist" is excluded
    Because the re-invitation cooldown is 90 days

  # --- Feedback Loop ---

  Scenario: Feedback loop adjusts message frequency
    Given CLI response rate has been below 10% for 2 consecutive weeks
    When @feedback-agent generates recommendations
    Then a recommendation to "decrease_frequency" for CLI is produced
    And the confidence score is above 0.7

  Scenario: Channel performance informs future routing
    Given user "warm-amber-light" has 0% CLI response rate
    And they have 60% email open rate
    When @channel-agent routes their next message
    Then the primary channel is "email" (not CLI)

  # --- Direction Recruiting ---

  Scenario: Direction agent identifies gap and recruits matching contributor
    Given the "PDF tools" category has gap_score > 10
    And user "keen-iron-blade" has published FFmpeg and ImageMagick recipes
    When @direction-agent matches contributors to gaps
    Then "keen-iron-blade" is identified as a match
    With relevance_score >= 3

  Scenario: Recruitment message shows real demand
    Given "PDF tools" had 230 searches this week
    When @direction-agent drafts a recruitment message
    Then the message includes "230" or the actual search volume
    And lists specific search queries people used

  # --- Human Approval Gate ---

  Scenario: Human approval gate blocks auto-send in Phase 1
    Given the autonomy phase is "Phase 1"
    And @outreach-agent has produced 5 message drafts
    When the drafts are queued
    Then all 5 have requires_approval set to true
    And none are automatically sent
    And a human operator must approve each one

  Scenario: Approved message is sent and tracked
    Given draft "msg_01ABC" is approved by human operator
    When the message is sent via the selected channel
    Then the sent_at timestamp is recorded
    And the message enters @feedback-agent tracking
    And the engagement queue status updates to "sent"

  Scenario: Rejected message is logged with reason
    Given draft "msg_02DEF" is rejected by human operator
    And the rejection reason is "too generic, needs specific recipe reference"
    When the rejection is processed
    Then the draft status updates to "rejected"
    And the reason is stored for @feedback-agent analysis
    And @outreach-agent learns from the rejection pattern
