//! Regen evaluator — decides whether `caro run` / `caro generate` should use
//! the cached lock, regenerate the lock entirely, or merely create an
//! exploratory challenger variant alongside the existing active one.
//!
//! Inputs (from PR-6 onward also include track-record stats and the runtime
//! journal): the parsed AST's intent hash, the lock's per-variant model /
//! caro-version / tool-versions, the current platform, and a set of mode
//! flags from the CLI (`--use-cached` / `--explore`).

use crate::caroml::ast::Task;
use crate::caroml::lock::Lock;
use sha2::{Digest, Sha256};

/// What the runtime should do for this invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Decision {
    /// The existing active variant is fresh; use it.
    UseCache,
    /// Must regenerate before running. Carries human-readable reasons.
    HardRegen { reasons: Vec<String> },
    /// Cache is fine, but produce a challenger variant in parallel
    /// (only effective when `--explore` is set; otherwise treated as UseCache).
    SoftExplore { reasons: Vec<String> },
}

impl Decision {
    pub fn is_use_cache(&self) -> bool {
        matches!(self, Self::UseCache)
    }

    pub fn is_hard_regen(&self) -> bool {
        matches!(self, Self::HardRegen { .. })
    }

    /// Human-readable reasons attached to the decision (empty for UseCache).
    pub fn reasons(&self) -> &[String] {
        match self {
            Self::UseCache => &[],
            Self::HardRegen { reasons } | Self::SoftExplore { reasons } => reasons.as_slice(),
        }
    }
}

/// Mode flags that influence the decision.
#[derive(Debug, Clone, Copy, Default)]
pub struct Mode {
    /// Skip all evaluation; force HardRegen (used by `caro upgrade`).
    pub force_regen: bool,
    /// Suppress all SoftExplore signals; cache is used unless HardRegen fires.
    /// (Used by `caro run --use-cached`.)
    pub use_cached: bool,
    /// Promote SoftExplore signals to actually generate a challenger.
    /// (Used by `caro run --explore`.)
    pub explore: bool,
}

/// Inputs the evaluator needs (so callers don't have to wire 6 args).
pub struct EvalInput<'a> {
    pub task: &'a Task,
    pub lock: Option<&'a Lock>,
    pub platform: &'a str,
    pub current_caro_version: &'a str,
    pub current_model: &'a str,
    pub current_backend: &'a str,
    pub mode: Mode,
}

/// Decide what action to take.
pub fn decide(input: &EvalInput<'_>) -> Decision {
    if input.mode.force_regen {
        return Decision::HardRegen {
            reasons: vec!["force_regen requested".into()],
        };
    }

    let lock = match input.lock {
        Some(l) => l,
        None => {
            return Decision::HardRegen {
                reasons: vec!["no lock file present".into()],
            };
        }
    };

    // Hard regen: intent_hash mismatch
    let computed_intent_hash = intent_hash(input.task);
    if lock.meta.intent_hash != computed_intent_hash {
        return Decision::HardRegen {
            reasons: vec![format!(
                "intent_hash mismatch (lock: {}, computed: {})",
                short_hash(&lock.meta.intent_hash),
                short_hash(&computed_intent_hash),
            )],
        };
    }

    // Hard regen: no active variant for this platform
    let has_platform = lock
        .steps
        .iter()
        .all(|s| s.active_variant(input.platform).is_some());
    if !has_platform || lock.steps.is_empty() {
        return Decision::HardRegen {
            reasons: vec![format!(
                "no active variant for platform `{}` on every step",
                input.platform
            )],
        };
    }

    if input.mode.use_cached {
        return Decision::UseCache;
    }

    // Soft explore: model / backend / caro_version drift on the active variant
    let mut soft: Vec<String> = Vec::new();
    for step in &lock.steps {
        if let Some(v) = step.active_variant(input.platform) {
            if v.model != input.current_model {
                soft.push(format!(
                    "step {}: variant generated by model `{}`, current is `{}`",
                    step.line, v.model, input.current_model
                ));
                break;
            }
            if v.backend != input.current_backend {
                soft.push(format!(
                    "step {}: variant generated by backend `{}`, current is `{}`",
                    step.line, v.backend, input.current_backend
                ));
                break;
            }
        }
    }
    if lock.meta.caro_version != input.current_caro_version {
        soft.push(format!(
            "lock written by caro {}, current is {}",
            lock.meta.caro_version, input.current_caro_version
        ));
    }

    if soft.is_empty() {
        Decision::UseCache
    } else if input.mode.explore {
        Decision::SoftExplore { reasons: soft }
    } else {
        // Reasons for re-generation exist but explore wasn't requested;
        // surface them via UseCache — the reasons are still visible in `caro why`.
        Decision::UseCache
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// SHA-256 hex digest of the parsed-and-normalized AST. v0.1 normalization
/// is minimal: title + why + needs + platform_pragmas + params + each
/// step's `intent` (post-LET-substitution). `notes` are intentionally
/// excluded so refining a hint to the LLM doesn't invalidate the lock.
pub fn intent_hash(task: &Task) -> String {
    let mut h = Sha256::new();
    h.update(b"TASK:");
    h.update(task.title.as_bytes());
    h.update(b"\nWHY:");
    if let Some(why) = &task.why {
        h.update(why.as_bytes());
    }
    h.update(b"\nNEED:");
    for need in &task.needs {
        h.update(need.as_bytes());
        h.update(b",");
    }
    h.update(b"\nON:");
    for p in &task.platform_pragmas {
        h.update(p.platform.as_bytes());
        h.update(b"|prefer=");
        for x in &p.prefer {
            h.update(x.as_bytes());
            h.update(b",");
        }
        h.update(b"|avoid=");
        for x in &p.avoid {
            h.update(x.as_bytes());
            h.update(b",");
        }
        h.update(b";");
    }
    h.update(b"\nLET:");
    for p in &task.params {
        h.update(p.name.as_bytes());
        h.update(b"=");
        h.update(p.value.as_bytes());
        h.update(b";");
    }
    h.update(b"\nDO:");
    for step in &task.steps {
        h.update(step.intent.as_bytes());
        h.update(b"\n");
    }
    format!("sha256:{}", hex_encode(&h.finalize()))
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(hex_nibble(b >> 4));
        s.push(hex_nibble(b & 0x0f));
    }
    s
}

fn hex_nibble(n: u8) -> char {
    match n {
        0..=9 => (b'0' + n) as char,
        _ => (b'a' + n - 10) as char,
    }
}

fn short_hash(s: &str) -> String {
    s.chars().take(15).collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::caroml::ast::{Param, PlatformPragma, Step, Task};
    use crate::caroml::lock::{Lock, Meta, Step as LockStep, Variant};
    use chrono::Utc;
    use std::collections::BTreeMap;

    fn sample_task() -> Task {
        Task {
            source_path: None,
            title: "demo".into(),
            why: Some("for tests".into()),
            needs: vec!["sudo".into()],
            platform_pragmas: vec![PlatformPragma {
                platform: "macos".into(),
                prefer: vec!["bsd-tools".into()],
                avoid: vec![],
            }],
            params: vec![Param {
                name: "p".into(),
                value: "/tmp".into(),
            }],
            steps: vec![Step {
                line: 5,
                intent: "do something".into(),
                raw_intent: "do something".into(),
                notes: vec![],
            }],
        }
    }

    fn sample_lock(intent_hash: &str) -> Lock {
        let mut lock = Lock::default();
        lock.meta = Meta {
            caro_version: "1.4.0".into(),
            intent_path: "tasks/demo.caro".into(),
            intent_hash: intent_hash.into(),
            supported_platforms: vec!["macos".into()],
            last_full_regen: Some(Utc::now()),
        };
        lock.steps = vec![LockStep {
            line: 5,
            intent: "do something".into(),
            intent_hash: "sha256:step".into(),
            notes: vec![],
            variants: vec![Variant {
                platform: "macos".into(),
                active: true,
                generation_id: "gen_a".into(),
                command: "ls".into(),
                reasoning: "test".into(),
                exports: vec![],
                imports: vec![],
                risk_level: "safe".into(),
                matched_patterns: vec![],
                warnings: vec![],
                confidence: 0.9,
                iterations: 1,
                validations: vec![],
                generated_at: Utc::now(),
                model: "smollm-1.7b".into(),
                backend: "embedded".into(),
                tool_versions: BTreeMap::new(),
                track_record: Default::default(),
                retired_at: None,
            }],
        }];
        lock
    }

    fn input<'a>(task: &'a Task, lock: Option<&'a Lock>, mode: Mode) -> EvalInput<'a> {
        EvalInput {
            task,
            lock,
            platform: "macos",
            current_caro_version: "1.4.0",
            current_model: "smollm-1.7b",
            current_backend: "embedded",
            mode,
        }
    }

    #[test]
    fn intent_hash_is_deterministic() {
        let a = intent_hash(&sample_task());
        let b = intent_hash(&sample_task());
        assert_eq!(a, b);
        assert!(a.starts_with("sha256:"));
    }

    #[test]
    fn intent_hash_changes_when_intent_changes() {
        let mut t1 = sample_task();
        let mut t2 = sample_task();
        t2.steps[0].intent = "do something else".into();
        assert_ne!(intent_hash(&t1), intent_hash(&t2));
        // notes don't affect hash:
        t1.steps[0].notes = vec!["a hint".into()];
        assert_eq!(intent_hash(&t1), intent_hash(&sample_task()));
    }

    #[test]
    fn no_lock_means_hard_regen() {
        let task = sample_task();
        let d = decide(&input(&task, None, Mode::default()));
        assert!(d.is_hard_regen());
    }

    #[test]
    fn intent_hash_mismatch_means_hard_regen() {
        let task = sample_task();
        let lock = sample_lock("sha256:wrong");
        let d = decide(&input(&task, Some(&lock), Mode::default()));
        assert!(d.is_hard_regen());
        assert!(d
            .reasons()
            .iter()
            .any(|r| r.contains("intent_hash mismatch")));
    }

    #[test]
    fn matching_intent_hash_means_use_cache() {
        let task = sample_task();
        let h = intent_hash(&task);
        let lock = sample_lock(&h);
        let d = decide(&input(&task, Some(&lock), Mode::default()));
        assert_eq!(d, Decision::UseCache);
    }

    #[test]
    fn force_regen_overrides_everything() {
        let task = sample_task();
        let h = intent_hash(&task);
        let lock = sample_lock(&h);
        let mode = Mode {
            force_regen: true,
            ..Mode::default()
        };
        let d = decide(&input(&task, Some(&lock), mode));
        assert!(d.is_hard_regen());
    }

    #[test]
    fn missing_platform_variant_means_hard_regen() {
        let task = sample_task();
        let h = intent_hash(&task);
        let lock = sample_lock(&h);
        let mut input_l = input(&task, Some(&lock), Mode::default());
        input_l.platform = "linux";
        let d = decide(&input_l);
        assert!(d.is_hard_regen());
        assert!(d
            .reasons()
            .iter()
            .any(|r| r.contains("no active variant for platform `linux`")));
    }

    #[test]
    fn model_drift_with_explore_yields_soft_explore() {
        let task = sample_task();
        let h = intent_hash(&task);
        let lock = sample_lock(&h);
        let mut input_l = input(&task, Some(&lock), Mode::default());
        input_l.current_model = "smollm-3.0b";
        input_l.mode.explore = true;
        let d = decide(&input_l);
        assert!(matches!(d, Decision::SoftExplore { .. }));
        assert!(d.reasons().iter().any(|r| r.contains("smollm-1.7b")));
    }

    #[test]
    fn model_drift_without_explore_still_use_cache() {
        let task = sample_task();
        let h = intent_hash(&task);
        let lock = sample_lock(&h);
        let mut input_l = input(&task, Some(&lock), Mode::default());
        input_l.current_model = "smollm-3.0b";
        // mode.explore = false (default)
        let d = decide(&input_l);
        assert_eq!(d, Decision::UseCache);
    }

    #[test]
    fn use_cached_mode_suppresses_soft_explore() {
        let task = sample_task();
        let h = intent_hash(&task);
        let lock = sample_lock(&h);
        let mut input_l = input(&task, Some(&lock), Mode::default());
        input_l.current_model = "smollm-3.0b";
        input_l.mode.explore = true;
        input_l.mode.use_cached = true;
        let d = decide(&input_l);
        assert_eq!(d, Decision::UseCache);
    }
}
