//! Runbook writer + drift detector.
//!
//! A runbook is the bash script generated by `caro export` from the active
//! variant of each step in a lock for one platform. Runbooks are committed
//! alongside the `.caro` and `.caro.lock` so any teammate (or CI) can run
//! `bash tasks/cleanup-logs.macos.sh` even without Caro installed.
//!
//! ## Format
//!
//! ```bash
//! #!/usr/bin/env bash
//! # Generated by Caro <ver> / <model> / <ts>
//! # Source:    tasks/<name>.caro    (intent_hash: sha256:...)
//! # Lock:      tasks/<name>.caro.lock
//! # Variant:   gen_<date>_<plat>_<a|b|...>  (active on <plat>, runs=N succeeded=M)
//! # Platform:  <plat>
//! # DO NOT EDIT BY HAND — `caro upgrade <name>` to refresh.
//! set -euo pipefail
//!
//! # TASK: <title>
//! # WHY:  <why>
//!
//! # DO <intent for step 1>
//! <command for step 1>
//!
//! # DO <intent for step 2>
//! <command for step 2>
//! ```
//!
//! ## Drift detection
//!
//! `compute_runbook_hash` hashes the body of a runbook excluding the
//! auto-stamped header lines (which contain timestamps and would otherwise
//! cause spurious drift). The lock stores the expected hash on each variant
//! and PR 6's `caro run` compares it before executing.

use crate::caroml::lock::{Lock, Step, Variant};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum RunbookError {
    #[error("no active variant for platform `{platform}` on step at line {line}")]
    NoActiveVariantForStep { line: usize, platform: String },
    #[error("no steps in lock — nothing to export")]
    EmptyLock,
    #[error("io error writing runbook: {0}")]
    Io(#[from] std::io::Error),
}

/// Build the runbook string for `lock` on `platform` (every step's active variant).
pub fn build_runbook(lock: &Lock, platform: &str) -> Result<String, RunbookError> {
    if lock.steps.is_empty() {
        return Err(RunbookError::EmptyLock);
    }

    let mut s = String::new();
    s.push_str(&header(lock, platform));
    s.push_str("set -euo pipefail\n\n");
    s.push_str(&format!("# TASK: {}\n", lock.task.title));
    if let Some(why) = &lock.task.why {
        s.push_str(&format!("# WHY:  {}\n", why));
    }
    s.push('\n');

    for step in &lock.steps {
        let variant = step
            .active_variant(platform)
            .ok_or_else(|| RunbookError::NoActiveVariantForStep {
                line: step.line,
                platform: platform.to_string(),
            })?;
        s.push_str(&format!("# DO {}\n", step.intent));
        s.push_str(variant.command.trim());
        s.push_str("\n\n");
    }

    Ok(s)
}

/// Atomically write the runbook to `<dir>/<base>.<platform>.sh`.
/// Returns the path written.
pub fn write_runbook(
    lock: &Lock,
    platform: &str,
    base_path_no_ext: &Path,
) -> Result<PathBuf, RunbookError> {
    let body = build_runbook(lock, platform)?;
    let path = runbook_path(base_path_no_ext, platform);
    let tmp = path_with_tmp(&path);
    std::fs::write(&tmp, body)?;
    std::fs::rename(&tmp, &path)?;
    Ok(path)
}

/// Compute the runbook path for a given `base` (typically the task's name
/// path without the `.caro` extension) and platform.
pub fn runbook_path(base: &Path, platform: &str) -> PathBuf {
    let mut buf = base.to_path_buf();
    let stem = buf
        .file_name()
        .map(|f| f.to_string_lossy().into_owned())
        .unwrap_or_default();
    let stem = stem.trim_end_matches(".caro").to_string();
    buf.set_file_name(format!("{}.{}.sh", stem, platform));
    buf
}

/// Hash a runbook's "body" (everything after the auto-stamped header).
/// Used by `caro run` (PR 5+) to detect manual edits to the runbook.
///
/// The hash skips lines that begin with `#` BEFORE the first non-comment
/// non-blank line (the header), then hashes everything that follows.
pub fn compute_runbook_hash(runbook: &str) -> String {
    let mut h = Sha256::new();
    let mut in_body = false;
    for line in runbook.lines() {
        if !in_body {
            let trimmed = line.trim_start();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            in_body = true;
        }
        h.update(line.as_bytes());
        h.update(b"\n");
    }
    let hex = h
        .finalize()
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();
    format!("sha256:{}", hex)
}

/// Read a runbook from disk and return its body hash.
pub fn read_and_hash(path: &Path) -> Result<String, RunbookError> {
    let body = std::fs::read_to_string(path)?;
    Ok(compute_runbook_hash(&body))
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

fn header(lock: &Lock, platform: &str) -> String {
    let active = first_active(lock, platform);
    let now = chrono::Utc::now().format("%Y-%m-%d %H:%M:%SZ");
    let mut s = String::new();
    s.push_str("#!/usr/bin/env bash\n");
    if let Some(v) = active {
        s.push_str(&format!(
            "# Generated by Caro {} / {} / {}\n",
            lock.meta.caro_version, v.model, now
        ));
        s.push_str(&format!(
            "# Source:    {}    (intent_hash: {})\n",
            lock.meta.intent_path, lock.meta.intent_hash
        ));
        s.push_str(&format!(
            "# Lock:      {}.lock\n",
            lock.meta.intent_path
        ));
        s.push_str(&format!(
            "# Variant:   {}  (active on {}, runs={} succeeded={})\n",
            v.generation_id,
            v.platform,
            v.track_record.runs,
            v.track_record.succeeded
        ));
        s.push_str(&format!("# Platform:  {}\n", platform));
    } else {
        s.push_str(&format!("# Generated by Caro {} / {}\n", lock.meta.caro_version, now));
        s.push_str(&format!("# Platform:  {}\n", platform));
    }
    s.push_str("# DO NOT EDIT BY HAND — `caro upgrade` to refresh from intent.\n");
    s
}

fn first_active<'a>(lock: &'a Lock, platform: &'a str) -> Option<&'a Variant> {
    lock.steps
        .iter()
        .find_map(|s: &Step| s.active_variant(platform))
}

fn path_with_tmp(path: &Path) -> PathBuf {
    let mut s = path.as_os_str().to_owned();
    s.push(".tmp");
    s.into()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::caroml::lock::{Lock, Meta, Step as LockStep, TaskMeta, Variant};
    use chrono::Utc;
    use std::collections::BTreeMap;

    fn variant(platform: &str, command: &str, gen_id: &str) -> Variant {
        Variant {
            platform: platform.into(),
            active: true,
            generation_id: gen_id.into(),
            command: command.into(),
            reasoning: "test".into(),
            exports: vec![],
            imports: vec![],
            risk_level: "safe".into(),
            matched_patterns: vec![],
            warnings: vec![],
            confidence: 1.0,
            iterations: 1,
            validations: vec![],
            generated_at: Utc::now(),
            model: "smollm-1.7b".into(),
            backend: "embedded".into(),
            tool_versions: BTreeMap::new(),
            track_record: Default::default(),
            retired_at: None,
        }
    }

    fn lock_with_two_steps() -> Lock {
        Lock {
            schema_version: crate::caroml::lock::SCHEMA_VERSION,
            meta: Meta {
                caro_version: "1.4.0".into(),
                intent_path: "tasks/cleanup-logs.caro".into(),
                intent_hash: "sha256:demo".into(),
                supported_platforms: vec!["macos".into(), "linux".into()],
                last_full_regen: Some(Utc::now()),
            },
            task: TaskMeta {
                title: "Clean up old logs".into(),
                why: Some("Free disk space".into()),
                needs: vec!["sudo".into()],
                prefers_by_platform: BTreeMap::new(),
                avoids_by_platform: BTreeMap::new(),
                params: BTreeMap::new(),
            },
            steps: vec![
                LockStep {
                    line: 5,
                    intent: "find log files".into(),
                    intent_hash: "sha256:s1".into(),
                    notes: vec![],
                    variants: vec![
                        variant("macos", "find /var/log -name '*.log'", "gen_a_macos"),
                        variant("linux", "find /var/log -name '*.log'", "gen_a_linux"),
                    ],
                },
                LockStep {
                    line: 6,
                    intent: "delete files older than 30 days".into(),
                    intent_hash: "sha256:s2".into(),
                    notes: vec![],
                    variants: vec![
                        variant(
                            "macos",
                            "find /var/log -name '*.log' -mtime +30 -delete",
                            "gen_b_macos",
                        ),
                        variant(
                            "linux",
                            "find /var/log -name '*.log' -mtime +30 -delete",
                            "gen_b_linux",
                        ),
                    ],
                },
            ],
            history: vec![],
        }
    }

    #[test]
    fn build_runbook_for_macos_includes_two_steps() {
        let lock = lock_with_two_steps();
        let body = build_runbook(&lock, "macos").unwrap();
        assert!(body.starts_with("#!/usr/bin/env bash"));
        assert!(body.contains("# TASK: Clean up old logs"));
        assert!(body.contains("# WHY:  Free disk space"));
        assert!(body.contains("# DO find log files"));
        assert!(body.contains("# DO delete files older than 30 days"));
        assert!(body.contains("find /var/log -name '*.log' -mtime +30 -delete"));
        assert!(body.contains("set -euo pipefail"));
    }

    #[test]
    fn build_runbook_errors_when_platform_missing() {
        let lock = lock_with_two_steps();
        match build_runbook(&lock, "windows") {
            Err(RunbookError::NoActiveVariantForStep { line: 5, .. }) => {}
            other => panic!("unexpected: {:?}", other),
        }
    }

    #[test]
    fn write_runbook_uses_platform_extension() {
        let dir = tempfile::tempdir().unwrap();
        let base = dir.path().join("cleanup-logs.caro");
        let lock = lock_with_two_steps();
        let path = write_runbook(&lock, "macos", &base).unwrap();
        assert!(path.to_string_lossy().ends_with("cleanup-logs.macos.sh"));
        assert!(path.exists());
        assert!(std::fs::read_to_string(&path)
            .unwrap()
            .contains("# Platform:  macos"));
    }

    #[test]
    fn runbook_path_strips_caro_extension_correctly() {
        let p = runbook_path(Path::new("tasks/cleanup-logs.caro"), "macos");
        assert_eq!(p, PathBuf::from("tasks/cleanup-logs.macos.sh"));

        let p2 = runbook_path(Path::new("tasks/cleanup-logs"), "linux");
        assert_eq!(p2, PathBuf::from("tasks/cleanup-logs.linux.sh"));
    }

    #[test]
    fn compute_runbook_hash_is_stable_across_header_changes() {
        // Two runbooks differing only in their auto-stamped headers should
        // hash identically.
        let a = "#!/usr/bin/env bash\n\
                 # Generated by Caro 1.4.0 / smollm / 2026-04-26 12:00:00Z\n\
                 # Variant:   gen_a\n\
                 set -euo pipefail\n\
                 echo hello\n";
        let b = "#!/usr/bin/env bash\n\
                 # Generated by Caro 1.4.0 / smollm / 2026-04-27 09:30:00Z\n\
                 # Variant:   gen_b\n\
                 set -euo pipefail\n\
                 echo hello\n";
        assert_eq!(compute_runbook_hash(a), compute_runbook_hash(b));
    }

    #[test]
    fn compute_runbook_hash_diverges_when_body_diverges() {
        let a = "#!/usr/bin/env bash\nset -euo pipefail\necho hello\n";
        let b = "#!/usr/bin/env bash\nset -euo pipefail\necho world\n";
        assert_ne!(compute_runbook_hash(a), compute_runbook_hash(b));
    }
}
