/**
 * Distribution & Shell Configuration Data
 *
 * Comprehensive metadata for all supported operating systems,
 * distributions, and shells. Used for display and theming.
 */

import type {
  DistroInfo,
  ShellInfo,
  LinuxDistro,
  WindowsEdition,
  MacOSVersion,
  ShellType,
  LinuxFamily,
  DistroTheme,
  OSFamily,
} from './distro-types';

// ============================================================================
// Linux Distribution Metadata
// ============================================================================

export const LINUX_DISTROS: Record<LinuxDistro, DistroInfo> = {
  // === Debian Family ===
  'debian': {
    id: 'debian',
    name: 'Debian',
    family: 'debian',
    icon: '🌀',
    color: '#A80030',
    packageManager: 'apt',
    website: 'https://debian.org',
    description: 'The Universal Operating System',
  },
  'ubuntu': {
    id: 'ubuntu',
    name: 'Ubuntu',
    family: 'debian',
    icon: '🟠',
    color: '#E95420',
    packageManager: 'apt',
    website: 'https://ubuntu.com',
    description: 'Linux for human beings',
  },
  'ubuntu-lts': {
    id: 'ubuntu-lts',
    name: 'Ubuntu LTS',
    shortName: 'Ubuntu',
    family: 'debian',
    icon: '🟠',
    color: '#E95420',
    packageManager: 'apt',
    description: 'Long-term support release',
  },
  'kubuntu': {
    id: 'kubuntu',
    name: 'Kubuntu',
    family: 'debian',
    icon: '🔷',
    color: '#0057A4',
    packageManager: 'apt',
    description: 'Ubuntu with KDE Plasma',
  },
  'xubuntu': {
    id: 'xubuntu',
    name: 'Xubuntu',
    family: 'debian',
    icon: '🐭',
    color: '#0044AA',
    packageManager: 'apt',
    description: 'Ubuntu with Xfce',
  },
  'lubuntu': {
    id: 'lubuntu',
    name: 'Lubuntu',
    family: 'debian',
    icon: '🪶',
    color: '#0068C8',
    packageManager: 'apt',
    description: 'Lightweight Ubuntu',
  },
  'ubuntu-mate': {
    id: 'ubuntu-mate',
    name: 'Ubuntu MATE',
    family: 'debian',
    icon: '🧉',
    color: '#87A556',
    packageManager: 'apt',
    description: 'Ubuntu with MATE desktop',
  },
  'ubuntu-studio': {
    id: 'ubuntu-studio',
    name: 'Ubuntu Studio',
    family: 'debian',
    icon: '🎵',
    color: '#0088CC',
    packageManager: 'apt',
    description: 'Ubuntu for content creators',
  },
  'ubuntu-server': {
    id: 'ubuntu-server',
    name: 'Ubuntu Server',
    family: 'debian',
    icon: '🖥️',
    color: '#E95420',
    packageManager: 'apt',
    description: 'Ubuntu for servers',
  },
  'linux-mint': {
    id: 'linux-mint',
    name: 'Linux Mint',
    family: 'debian',
    icon: '🌿',
    color: '#87CF3E',
    packageManager: 'apt',
    website: 'https://linuxmint.com',
    description: 'From freedom came elegance',
  },
  'linux-mint-lmde': {
    id: 'linux-mint-lmde',
    name: 'LMDE',
    family: 'debian',
    icon: '🌿',
    color: '#87CF3E',
    packageManager: 'apt',
    description: 'Linux Mint Debian Edition',
  },
  'pop-os': {
    id: 'pop-os',
    name: 'Pop!_OS',
    family: 'debian',
    icon: '🚀',
    color: '#48B9C7',
    packageManager: 'apt',
    website: 'https://pop.system76.com',
    description: 'For STEM and creators',
  },
  'elementary-os': {
    id: 'elementary-os',
    name: 'elementary OS',
    family: 'debian',
    icon: '⚡',
    color: '#64BAFF',
    packageManager: 'apt',
    website: 'https://elementary.io',
    description: 'The thoughtful, capable, and ethical OS',
  },
  'zorin-os': {
    id: 'zorin-os',
    name: 'Zorin OS',
    family: 'debian',
    icon: '💎',
    color: '#0CC1F1',
    packageManager: 'apt',
    website: 'https://zorin.com',
    description: 'Make your computer better',
  },
  'mx-linux': {
    id: 'mx-linux',
    name: 'MX Linux',
    family: 'debian',
    icon: '🔶',
    color: '#4A7B24',
    packageManager: 'apt',
    website: 'https://mxlinux.org',
    description: 'Midweight, simple, stable',
  },
  'antiX': {
    id: 'antiX',
    name: 'antiX',
    family: 'debian',
    icon: '⚡',
    color: '#FF6600',
    packageManager: 'apt',
    description: 'Fast, lightweight, and easy to install',
  },
  'kali-linux': {
    id: 'kali-linux',
    name: 'Kali Linux',
    family: 'debian',
    icon: '🐉',
    color: '#367BF0',
    packageManager: 'apt',
    website: 'https://kali.org',
    description: 'The most advanced penetration testing distro',
  },
  'parrot-os': {
    id: 'parrot-os',
    name: 'Parrot OS',
    family: 'debian',
    icon: '🦜',
    color: '#00D4AA',
    packageManager: 'apt',
    website: 'https://parrotsec.org',
    description: 'Security and privacy',
  },
  'raspbian': {
    id: 'raspbian',
    name: 'Raspbian',
    family: 'debian',
    icon: '🍇',
    color: '#C51A4A',
    packageManager: 'apt',
    description: 'Legacy Raspberry Pi OS',
  },
  'raspberry-pi-os': {
    id: 'raspberry-pi-os',
    name: 'Raspberry Pi OS',
    family: 'debian',
    icon: '🍓',
    color: '#C51A4A',
    packageManager: 'apt',
    website: 'https://raspberrypi.org',
    description: 'The official Raspberry Pi OS',
  },
  'deepin': {
    id: 'deepin',
    name: 'Deepin',
    family: 'debian',
    icon: '🌊',
    color: '#2CA7F8',
    packageManager: 'apt',
    website: 'https://deepin.org',
    description: 'Beautiful and elegant',
  },
  'bodhi-linux': {
    id: 'bodhi-linux',
    name: 'Bodhi Linux',
    family: 'debian',
    icon: '🍃',
    color: '#006400',
    packageManager: 'apt',
    description: 'Enlightened Linux',
  },
  'peppermint-os': {
    id: 'peppermint-os',
    name: 'Peppermint OS',
    family: 'debian',
    icon: '🍬',
    color: '#CC0000',
    packageManager: 'apt',
    description: 'Cloud-focused lightweight distro',
  },
  'sparky-linux': {
    id: 'sparky-linux',
    name: 'SparkyLinux',
    family: 'debian',
    icon: '⚡',
    color: '#FF4500',
    packageManager: 'apt',
    description: 'Fast, lightweight, customizable',
  },
  'lmde': {
    id: 'lmde',
    name: 'LMDE',
    family: 'debian',
    icon: '🌿',
    color: '#87CF3E',
    packageManager: 'apt',
    description: 'Linux Mint Debian Edition',
  },
  'devuan': {
    id: 'devuan',
    name: 'Devuan',
    family: 'debian',
    icon: '🔓',
    color: '#333366',
    packageManager: 'apt',
    website: 'https://devuan.org',
    description: 'Debian without systemd',
  },
  'bunsenlabs': {
    id: 'bunsenlabs',
    name: 'BunsenLabs',
    family: 'debian',
    icon: '🔥',
    color: '#333333',
    packageManager: 'apt',
    description: 'Openbox on Debian',
  },
  'q4os': {
    id: 'q4os',
    name: 'Q4OS',
    family: 'debian',
    icon: '4️⃣',
    color: '#0066CC',
    packageManager: 'apt',
    description: 'Desktop operating system',
  },
  'kde-neon': {
    id: 'kde-neon',
    name: 'KDE Neon',
    family: 'debian',
    icon: '💠',
    color: '#1D99F3',
    packageManager: 'apt',
    website: 'https://neon.kde.org',
    description: 'Latest KDE on Ubuntu LTS',
  },
  'tails': {
    id: 'tails',
    name: 'Tails',
    family: 'debian',
    icon: '🔒',
    color: '#56347C',
    packageManager: 'apt',
    website: 'https://tails.net',
    description: 'Privacy and anonymity',
  },
  'pureos': {
    id: 'pureos',
    name: 'PureOS',
    family: 'debian',
    icon: '🛡️',
    color: '#3584E4',
    packageManager: 'apt',
    website: 'https://pureos.net',
    description: 'Freedom-respecting OS',
  },
  'steamos': {
    id: 'steamos',
    name: 'SteamOS',
    family: 'debian',
    icon: '🎮',
    color: '#1B2838',
    packageManager: 'apt',
    description: 'Valve\'s gaming-focused OS',
  },

  // === Red Hat Family ===
  'fedora': {
    id: 'fedora',
    name: 'Fedora',
    family: 'redhat',
    icon: '🎩',
    color: '#3C6EB4',
    packageManager: 'dnf',
    website: 'https://fedoraproject.org',
    description: 'Freedom. Friends. Features. First.',
  },
  'fedora-silverblue': {
    id: 'fedora-silverblue',
    name: 'Fedora Silverblue',
    family: 'redhat',
    icon: '🔵',
    color: '#0B57A4',
    packageManager: 'rpm-ostree',
    description: 'Immutable Fedora with GNOME',
  },
  'fedora-kinoite': {
    id: 'fedora-kinoite',
    name: 'Fedora Kinoite',
    family: 'redhat',
    icon: '🔷',
    color: '#1D99F3',
    packageManager: 'rpm-ostree',
    description: 'Immutable Fedora with KDE',
  },
  'rhel': {
    id: 'rhel',
    name: 'RHEL',
    shortName: 'RHEL',
    family: 'redhat',
    icon: '🎩',
    color: '#CC0000',
    packageManager: 'dnf',
    website: 'https://redhat.com',
    description: 'Red Hat Enterprise Linux',
  },
  'centos': {
    id: 'centos',
    name: 'CentOS',
    family: 'redhat',
    icon: '🟣',
    color: '#932279',
    packageManager: 'dnf',
    description: 'Community Enterprise OS (EOL)',
  },
  'centos-stream': {
    id: 'centos-stream',
    name: 'CentOS Stream',
    family: 'redhat',
    icon: '🟣',
    color: '#932279',
    packageManager: 'dnf',
    website: 'https://centos.org',
    description: 'The upstream for RHEL',
  },
  'rocky-linux': {
    id: 'rocky-linux',
    name: 'Rocky Linux',
    family: 'redhat',
    icon: '🪨',
    color: '#10B981',
    packageManager: 'dnf',
    website: 'https://rockylinux.org',
    description: 'CentOS replacement',
  },
  'alma-linux': {
    id: 'alma-linux',
    name: 'AlmaLinux',
    family: 'redhat',
    icon: '🌐',
    color: '#0F4266',
    packageManager: 'dnf',
    website: 'https://almalinux.org',
    description: 'Forever-free enterprise OS',
  },
  'oracle-linux': {
    id: 'oracle-linux',
    name: 'Oracle Linux',
    family: 'redhat',
    icon: '🔴',
    color: '#C74634',
    packageManager: 'dnf',
    description: 'Oracle\'s enterprise Linux',
  },
  'amazon-linux': {
    id: 'amazon-linux',
    name: 'Amazon Linux',
    family: 'redhat',
    icon: '📦',
    color: '#FF9900',
    packageManager: 'dnf',
    description: 'AWS-optimized Linux',
  },
  'nobara': {
    id: 'nobara',
    name: 'Nobara',
    family: 'redhat',
    icon: '🎮',
    color: '#6C63FF',
    packageManager: 'dnf',
    website: 'https://nobaraproject.org',
    description: 'Gaming-focused Fedora',
  },
  'ultramarine': {
    id: 'ultramarine',
    name: 'Ultramarine',
    family: 'redhat',
    icon: '🌊',
    color: '#4169E1',
    packageManager: 'dnf',
    description: 'Fedora with extras',
  },
  'qubes-os': {
    id: 'qubes-os',
    name: 'Qubes OS',
    family: 'redhat',
    icon: '🔐',
    color: '#3874D8',
    packageManager: 'dnf',
    website: 'https://qubes-os.org',
    description: 'Reasonably secure OS',
  },
  'scientific-linux': {
    id: 'scientific-linux',
    name: 'Scientific Linux',
    family: 'redhat',
    icon: '🔬',
    color: '#1F8ACB',
    packageManager: 'yum',
    description: 'For scientific computing (EOL)',
  },
  'clearos': {
    id: 'clearos',
    name: 'ClearOS',
    family: 'redhat',
    icon: '🏢',
    color: '#00A4E4',
    packageManager: 'yum',
    description: 'Small business server OS',
  },

  // === Arch Family ===
  'arch-linux': {
    id: 'arch-linux',
    name: 'Arch Linux',
    family: 'arch',
    icon: '🏔️',
    color: '#1793D1',
    packageManager: 'pacman',
    website: 'https://archlinux.org',
    description: 'Keep It Simple, Stupid',
  },
  'manjaro': {
    id: 'manjaro',
    name: 'Manjaro',
    family: 'arch',
    icon: '🌲',
    color: '#35BF5C',
    packageManager: 'pacman',
    website: 'https://manjaro.org',
    description: 'Arch made user-friendly',
  },
  'endeavouros': {
    id: 'endeavouros',
    name: 'EndeavourOS',
    family: 'arch',
    icon: '🚀',
    color: '#7F3FBF',
    packageManager: 'pacman',
    website: 'https://endeavouros.com',
    description: 'Arch-based, terminal-centric',
  },
  'garuda-linux': {
    id: 'garuda-linux',
    name: 'Garuda Linux',
    family: 'arch',
    icon: '🦅',
    color: '#FF6600',
    packageManager: 'pacman',
    website: 'https://garudalinux.org',
    description: 'Performance-focused Arch',
  },
  'arco-linux': {
    id: 'arco-linux',
    name: 'ArcoLinux',
    family: 'arch',
    icon: '📐',
    color: '#5277C3',
    packageManager: 'pacman',
    description: 'Learn-by-doing Arch',
  },
  'artix-linux': {
    id: 'artix-linux',
    name: 'Artix Linux',
    family: 'arch',
    icon: '🎨',
    color: '#10A0DE',
    packageManager: 'pacman',
    website: 'https://artixlinux.org',
    description: 'Arch without systemd',
  },
  'blackarch': {
    id: 'blackarch',
    name: 'BlackArch',
    family: 'arch',
    icon: '🕵️',
    color: '#000000',
    packageManager: 'pacman',
    website: 'https://blackarch.org',
    description: 'Pen testing on Arch',
  },
  'archcraft': {
    id: 'archcraft',
    name: 'Archcraft',
    family: 'arch',
    icon: '🎭',
    color: '#7AA2F7',
    packageManager: 'pacman',
    website: 'https://archcraft.io',
    description: 'Beautiful, minimal Arch',
  },
  'cachyos': {
    id: 'cachyos',
    name: 'CachyOS',
    family: 'arch',
    icon: '⚡',
    color: '#00BCD4',
    packageManager: 'pacman',
    website: 'https://cachyos.org',
    description: 'Speed-optimized Arch',
  },
  'crystal-linux': {
    id: 'crystal-linux',
    name: 'Crystal Linux',
    family: 'arch',
    icon: '💎',
    color: '#A855F7',
    packageManager: 'pacman',
    description: 'Modern Arch experience',
  },
  'rebornos': {
    id: 'rebornos',
    name: 'RebornOS',
    family: 'arch',
    icon: '🌅',
    color: '#FF8C00',
    packageManager: 'pacman',
    description: 'Arch made accessible',
  },
  'archbang': {
    id: 'archbang',
    name: 'ArchBang',
    family: 'arch',
    icon: '💥',
    color: '#666666',
    packageManager: 'pacman',
    description: 'Minimal Arch with Openbox',
  },
  'hyperbola': {
    id: 'hyperbola',
    name: 'Hyperbola',
    family: 'arch',
    icon: '∞',
    color: '#333333',
    packageManager: 'pacman',
    website: 'https://hyperbola.info',
    description: '100% libre Arch',
  },
  'parabola': {
    id: 'parabola',
    name: 'Parabola',
    family: 'arch',
    icon: '📈',
    color: '#333333',
    packageManager: 'pacman',
    website: 'https://parabola.nu',
    description: 'Fully free Arch',
  },

  // === SUSE Family ===
  'opensuse-tumbleweed': {
    id: 'opensuse-tumbleweed',
    name: 'openSUSE Tumbleweed',
    shortName: 'Tumbleweed',
    family: 'suse',
    icon: '🦎',
    color: '#73BA25',
    packageManager: 'zypper',
    website: 'https://opensuse.org',
    description: 'Rolling release openSUSE',
  },
  'opensuse-leap': {
    id: 'opensuse-leap',
    name: 'openSUSE Leap',
    shortName: 'Leap',
    family: 'suse',
    icon: '🦎',
    color: '#73BA25',
    packageManager: 'zypper',
    description: 'Stable release openSUSE',
  },
  'sles': {
    id: 'sles',
    name: 'SUSE Linux Enterprise',
    shortName: 'SLES',
    family: 'suse',
    icon: '🦎',
    color: '#02D35F',
    packageManager: 'zypper',
    description: 'SUSE Enterprise Linux',
  },
  'gecko-linux': {
    id: 'gecko-linux',
    name: 'GeckoLinux',
    family: 'suse',
    icon: '🦎',
    color: '#73BA25',
    packageManager: 'zypper',
    description: 'Polished openSUSE',
  },

  // === Gentoo Family ===
  'gentoo': {
    id: 'gentoo',
    name: 'Gentoo',
    family: 'gentoo',
    icon: '🐧',
    color: '#54487A',
    packageManager: 'emerge',
    website: 'https://gentoo.org',
    description: 'Compile everything',
  },
  'funtoo': {
    id: 'funtoo',
    name: 'Funtoo',
    family: 'gentoo',
    icon: '🎉',
    color: '#6600CC',
    packageManager: 'emerge',
    website: 'https://funtoo.org',
    description: 'Gentoo by Daniel Robbins',
  },
  'calculate-linux': {
    id: 'calculate-linux',
    name: 'Calculate Linux',
    family: 'gentoo',
    icon: '🧮',
    color: '#5C5CFF',
    packageManager: 'emerge',
    description: 'User-friendly Gentoo',
  },
  'sabayon': {
    id: 'sabayon',
    name: 'Sabayon',
    family: 'gentoo',
    icon: '🍝',
    color: '#4C4C4C',
    packageManager: 'entropy',
    description: 'Gentoo for humans (EOL)',
  },
  'redcore': {
    id: 'redcore',
    name: 'Redcore Linux',
    family: 'gentoo',
    icon: '🔴',
    color: '#CC0000',
    packageManager: 'emerge',
    description: 'Hardened Gentoo',
  },

  // === Independent / Other ===
  'nixos': {
    id: 'nixos',
    name: 'NixOS',
    family: 'independent',
    icon: '❄️',
    color: '#5277C3',
    packageManager: 'nix',
    website: 'https://nixos.org',
    description: 'Purely functional Linux',
  },
  'void-linux': {
    id: 'void-linux',
    name: 'Void Linux',
    family: 'independent',
    icon: '🕳️',
    color: '#478061',
    packageManager: 'xbps',
    website: 'https://voidlinux.org',
    description: 'Independent, rolling release',
  },
  'alpine-linux': {
    id: 'alpine-linux',
    name: 'Alpine Linux',
    family: 'alpine',
    icon: '⛰️',
    color: '#0D597F',
    packageManager: 'apk',
    website: 'https://alpinelinux.org',
    description: 'Security-oriented, lightweight',
  },
  'slackware': {
    id: 'slackware',
    name: 'Slackware',
    family: 'slackware',
    icon: '📦',
    color: '#000080',
    packageManager: 'slackpkg',
    website: 'https://slackware.com',
    description: 'The oldest surviving distro',
  },
  'solus': {
    id: 'solus',
    name: 'Solus',
    family: 'independent',
    icon: '☀️',
    color: '#5294E2',
    packageManager: 'eopkg',
    website: 'https://getsol.us',
    description: 'Desktop-focused, independent',
  },
  'pclinuxos': {
    id: 'pclinuxos',
    name: 'PCLinuxOS',
    family: 'independent',
    icon: '🖥️',
    color: '#0040FF',
    packageManager: 'apt-rpm',
    description: 'Rolling release, user-friendly',
  },
  'mageia': {
    id: 'mageia',
    name: 'Mageia',
    family: 'independent',
    icon: '🧙',
    color: '#2397D4',
    packageManager: 'urpmi',
    website: 'https://mageia.org',
    description: 'Community Mandriva fork',
  },
  'openmandriva': {
    id: 'openmandriva',
    name: 'OpenMandriva',
    family: 'independent',
    icon: '⭐',
    color: '#2E8BC0',
    packageManager: 'dnf',
    website: 'https://openmandriva.org',
    description: 'Mandriva\'s successor',
  },
  'puppy-linux': {
    id: 'puppy-linux',
    name: 'Puppy Linux',
    family: 'independent',
    icon: '🐶',
    color: '#0066CC',
    packageManager: 'ppm',
    description: 'Tiny and portable',
  },
  'tiny-core': {
    id: 'tiny-core',
    name: 'Tiny Core',
    family: 'independent',
    icon: '🔬',
    color: '#3366FF',
    packageManager: 'tce',
    description: 'Minimalist at 16MB',
  },
  'porteus': {
    id: 'porteus',
    name: 'Porteus',
    family: 'slackware',
    icon: '💾',
    color: '#0066CC',
    packageManager: 'slackpkg',
    description: 'Portable Slackware-based',
  },
  'slitaz': {
    id: 'slitaz',
    name: 'SliTaz',
    family: 'independent',
    icon: '🍕',
    color: '#D94600',
    packageManager: 'tazpkg',
    description: 'Simple, fast, and low resource',
  },
  'clear-linux': {
    id: 'clear-linux',
    name: 'Clear Linux',
    family: 'independent',
    icon: '💡',
    color: '#0071C5',
    packageManager: 'swupd',
    description: 'Intel-optimized performance',
  },
  'chrome-os': {
    id: 'chrome-os',
    name: 'ChromeOS',
    family: 'independent',
    icon: '🌐',
    color: '#4285F4',
    packageManager: 'N/A',
    description: 'Google\'s cloud-first OS',
  },
  'chromium-os': {
    id: 'chromium-os',
    name: 'Chromium OS',
    family: 'independent',
    icon: '🌐',
    color: '#4285F4',
    packageManager: 'N/A',
    description: 'Open-source ChromeOS',
  },
  'guix': {
    id: 'guix',
    name: 'GNU Guix',
    family: 'independent',
    icon: '🐃',
    color: '#F1AD00',
    packageManager: 'guix',
    website: 'https://guix.gnu.org',
    description: 'Functional package management',
  },
  'bedrock-linux': {
    id: 'bedrock-linux',
    name: 'Bedrock Linux',
    family: 'independent',
    icon: '🪨',
    color: '#555555',
    packageManager: 'Multiple',
    description: 'Mix packages from any distro',
  },
  'kiss-linux': {
    id: 'kiss-linux',
    name: 'KISS Linux',
    family: 'independent',
    icon: '💋',
    color: '#222222',
    packageManager: 'kiss',
    description: 'Keep It Simple, Stupid',
  },
  'gobo-linux': {
    id: 'gobo-linux',
    name: 'GoboLinux',
    family: 'independent',
    icon: '📂',
    color: '#00AA00',
    packageManager: 'Compile',
    description: 'Alternative filesystem hierarchy',
  },

  // === BSD Family ===
  'freebsd': {
    id: 'freebsd',
    name: 'FreeBSD',
    family: 'bsd' as any,
    icon: '😈',
    color: '#AB2B28',
    packageManager: 'pkg',
    website: 'https://freebsd.org',
    description: 'The Power to Serve',
  },
  'openbsd': {
    id: 'openbsd',
    name: 'OpenBSD',
    family: 'bsd' as any,
    icon: '🐡',
    color: '#F2CA30',
    packageManager: 'pkg_add',
    website: 'https://openbsd.org',
    description: 'Free, Functional & Secure',
  },
  'netbsd': {
    id: 'netbsd',
    name: 'NetBSD',
    family: 'bsd' as any,
    icon: '🚩',
    color: '#FF6600',
    packageManager: 'pkgsrc',
    website: 'https://netbsd.org',
    description: 'Of course it runs NetBSD',
  },
  'dragonflybsd': {
    id: 'dragonflybsd',
    name: 'DragonFly BSD',
    family: 'bsd' as any,
    icon: '🐲',
    color: '#991133',
    packageManager: 'pkg',
    website: 'https://dragonflybsd.org',
    description: 'Logical continuation of FreeBSD 4.x',
  },
  'ghostbsd': {
    id: 'ghostbsd',
    name: 'GhostBSD',
    family: 'bsd' as any,
    icon: '👻',
    color: '#4D4D4D',
    packageManager: 'pkg',
    website: 'https://ghostbsd.org',
    description: 'User-friendly FreeBSD',
  },
  'trueos': {
    id: 'trueos',
    name: 'TrueOS',
    family: 'bsd' as any,
    icon: '🔷',
    color: '#0066CC',
    packageManager: 'pkg',
    description: 'FreeBSD for desktop (discontinued)',
  },
  'midnightbsd': {
    id: 'midnightbsd',
    name: 'MidnightBSD',
    family: 'bsd' as any,
    icon: '🌙',
    color: '#1a1a2e',
    packageManager: 'mport',
    website: 'https://midnightbsd.org',
    description: 'Desktop BSD from FreeBSD',
  },

  // Fallback
  'linux-other': {
    id: 'linux-other',
    name: 'Other Linux',
    family: 'other',
    icon: '🐧',
    color: '#FCC624',
    packageManager: 'Unknown',
    description: 'Other Linux distribution',
  },
};

// ============================================================================
// Windows Metadata
// ============================================================================

export const WINDOWS_EDITIONS: Record<WindowsEdition, DistroInfo> = {
  'windows-11': {
    id: 'windows-11',
    name: 'Windows 11',
    family: 'windows',
    icon: '🪟',
    color: '#0078D4',
    packageManager: 'winget',
    description: 'The latest Windows',
  },
  'windows-10': {
    id: 'windows-10',
    name: 'Windows 10',
    family: 'windows',
    icon: '🪟',
    color: '#0078D4',
    packageManager: 'winget',
    description: 'Still going strong',
  },
  'windows-server': {
    id: 'windows-server',
    name: 'Windows Server',
    family: 'windows',
    icon: '🖥️',
    color: '#0078D4',
    packageManager: 'winget',
    description: 'Server edition',
  },
  'windows-wsl': {
    id: 'windows-wsl',
    name: 'WSL',
    shortName: 'WSL',
    family: 'windows',
    icon: '🐧',
    color: '#FCC624',
    packageManager: 'apt/dnf/pacman',
    description: 'Windows Subsystem for Linux',
  },
  'windows-other': {
    id: 'windows-other',
    name: 'Windows',
    family: 'windows',
    icon: '🪟',
    color: '#0078D4',
    packageManager: 'Unknown',
    description: 'Other Windows version',
  },
};

// ============================================================================
// macOS Metadata
// ============================================================================

export const MACOS_VERSIONS: Record<MacOSVersion, DistroInfo> = {
  'macos-sequoia': {
    id: 'macos-sequoia',
    name: 'macOS Sequoia',
    shortName: 'Sequoia',
    family: 'macos',
    icon: '🍎',
    color: '#000000',
    packageManager: 'brew',
    description: 'macOS 15',
  },
  'macos-sonoma': {
    id: 'macos-sonoma',
    name: 'macOS Sonoma',
    shortName: 'Sonoma',
    family: 'macos',
    icon: '🍎',
    color: '#000000',
    packageManager: 'brew',
    description: 'macOS 14',
  },
  'macos-ventura': {
    id: 'macos-ventura',
    name: 'macOS Ventura',
    shortName: 'Ventura',
    family: 'macos',
    icon: '🍎',
    color: '#000000',
    packageManager: 'brew',
    description: 'macOS 13',
  },
  'macos-monterey': {
    id: 'macos-monterey',
    name: 'macOS Monterey',
    shortName: 'Monterey',
    family: 'macos',
    icon: '🍎',
    color: '#000000',
    packageManager: 'brew',
    description: 'macOS 12',
  },
  'macos-bigsur': {
    id: 'macos-bigsur',
    name: 'macOS Big Sur',
    shortName: 'Big Sur',
    family: 'macos',
    icon: '🍎',
    color: '#000000',
    packageManager: 'brew',
    description: 'macOS 11',
  },
  'macos-older': {
    id: 'macos-older',
    name: 'macOS',
    family: 'macos',
    icon: '🍎',
    color: '#000000',
    packageManager: 'brew',
    description: 'Older macOS version',
  },
};

// ============================================================================
// Shell Metadata
// ============================================================================

export const SHELLS: Record<ShellType, ShellInfo> = {
  // POSIX shells
  'bash': {
    id: 'bash',
    name: 'Bash',
    icon: '💲',
    color: '#4EAA25',
    website: 'https://www.gnu.org/software/bash/',
    description: 'Bourne Again Shell',
  },
  'zsh': {
    id: 'zsh',
    name: 'Zsh',
    icon: '⚡',
    color: '#89E051',
    website: 'https://www.zsh.org/',
    description: 'Z Shell - The extended Bourne shell',
  },
  'fish': {
    id: 'fish',
    name: 'Fish',
    icon: '🐟',
    color: '#FF8C00',
    website: 'https://fishshell.com/',
    description: 'Friendly Interactive Shell',
  },
  'sh': {
    id: 'sh',
    name: 'sh',
    icon: '📜',
    color: '#333333',
    description: 'POSIX Shell',
  },
  'dash': {
    id: 'dash',
    name: 'dash',
    icon: '➖',
    color: '#333333',
    description: 'Debian Almquist Shell',
  },
  'ksh': {
    id: 'ksh',
    name: 'Ksh',
    icon: '🐚',
    color: '#555555',
    description: 'Korn Shell',
  },
  'tcsh': {
    id: 'tcsh',
    name: 'Tcsh',
    icon: '🐚',
    color: '#555555',
    description: 'TENEX C Shell',
  },
  'csh': {
    id: 'csh',
    name: 'Csh',
    icon: '🐚',
    color: '#555555',
    description: 'C Shell',
  },
  'ash': {
    id: 'ash',
    name: 'Ash',
    icon: '🌲',
    color: '#333333',
    description: 'Almquist Shell',
  },

  // Modern shells
  'nushell': {
    id: 'nushell',
    name: 'Nushell',
    icon: '🦀',
    color: '#4B9CD3',
    website: 'https://www.nushell.sh/',
    description: 'Modern shell with structured data',
  },
  'elvish': {
    id: 'elvish',
    name: 'Elvish',
    icon: '🧝',
    color: '#5B4699',
    website: 'https://elv.sh/',
    description: 'Expressive programming language and shell',
  },
  'ion': {
    id: 'ion',
    name: 'Ion',
    icon: '⚛️',
    color: '#3E863D',
    description: 'Modern shell by Redox',
  },
  'xonsh': {
    id: 'xonsh',
    name: 'Xonsh',
    icon: '🐚',
    color: '#FFCC00',
    website: 'https://xon.sh/',
    description: 'Python-powered shell',
  },
  'oil': {
    id: 'oil',
    name: 'Oil Shell',
    icon: '🛢️',
    color: '#FFFF00',
    website: 'https://www.oilshell.org/',
    description: 'Bash-compatible with modern features',
  },
  'murex': {
    id: 'murex',
    name: 'Murex',
    icon: '🐡',
    color: '#FF6B6B',
    website: 'https://murex.rocks/',
    description: 'Typed shell and scripting language',
  },
  'yash': {
    id: 'yash',
    name: 'Yash',
    icon: '🐚',
    color: '#666666',
    description: 'Yet Another Shell',
  },
  'rc': {
    id: 'rc',
    name: 'rc',
    icon: '📐',
    color: '#333333',
    description: 'Plan 9 shell',
  },

  // Windows shells
  'powershell': {
    id: 'powershell',
    name: 'PowerShell',
    icon: '💙',
    color: '#012456',
    website: 'https://docs.microsoft.com/powershell/',
    description: 'Windows PowerShell',
  },
  'pwsh': {
    id: 'pwsh',
    name: 'PowerShell Core',
    icon: '💙',
    color: '#5391FE',
    website: 'https://github.com/PowerShell/PowerShell',
    description: 'Cross-platform PowerShell',
  },
  'cmd': {
    id: 'cmd',
    name: 'Command Prompt',
    icon: '📦',
    color: '#000000',
    description: 'Windows Command Prompt',
  },

  'other': {
    id: 'other',
    name: 'Other',
    icon: '🐚',
    color: '#666666',
    description: 'Other shell',
  },
};

// ============================================================================
// Theme Mappings
// ============================================================================

/**
 * Get theme customization for a given OS/distro
 */
export function getDistroTheme(osFamily: OSFamily, distro?: string | null): DistroTheme {
  const defaultTheme: DistroTheme = {
    accentColor: '#ff8c42', // Caro orange
    secondaryColor: '#ea4aaa', // Caro pink
    terminalBg: '#1e1e2e',
    terminalText: '#cdd6f4',
    promptStyle: 'default',
    cssClass: 'distro-default',
  };

  if (osFamily === 'macos') {
    return {
      ...defaultTheme,
      accentColor: '#0071e3',
      secondaryColor: '#333333',
      cssClass: 'distro-macos',
    };
  }

  if (osFamily === 'windows') {
    return {
      ...defaultTheme,
      accentColor: '#0078D4',
      secondaryColor: '#50e6ff',
      promptStyle: 'powershell',
      cssClass: 'distro-windows',
    };
  }

  // Linux distro-specific themes
  if (distro && LINUX_DISTROS[distro as LinuxDistro]) {
    const info = LINUX_DISTROS[distro as LinuxDistro];
    return {
      accentColor: info.color,
      secondaryColor: defaultTheme.secondaryColor,
      terminalBg: '#1e1e2e',
      terminalText: '#cdd6f4',
      promptStyle: 'bash',
      cssClass: `distro-${distro.replace(/-/g, '_')}`,
    };
  }

  return defaultTheme;
}

// ============================================================================
// Category Groups for UI
// ============================================================================

export const DISTRO_CATEGORIES = {
  popular: [
    'ubuntu', 'fedora', 'arch-linux', 'linux-mint', 'debian',
    'pop-os', 'manjaro', 'opensuse-tumbleweed', 'elementary-os', 'zorin-os',
  ] as LinuxDistro[],

  debian: [
    'debian', 'ubuntu', 'linux-mint', 'pop-os', 'elementary-os',
    'zorin-os', 'mx-linux', 'kali-linux', 'raspberry-pi-os', 'kde-neon',
  ] as LinuxDistro[],

  redhat: [
    'fedora', 'rhel', 'rocky-linux', 'alma-linux', 'centos-stream',
    'nobara', 'fedora-silverblue',
  ] as LinuxDistro[],

  arch: [
    'arch-linux', 'manjaro', 'endeavouros', 'garuda-linux', 'artix-linux',
    'cachyos', 'archcraft',
  ] as LinuxDistro[],

  immutable: [
    'fedora-silverblue', 'fedora-kinoite', 'nixos', 'guix',
  ] as LinuxDistro[],

  enterprise: [
    'rhel', 'sles', 'ubuntu-server', 'rocky-linux', 'alma-linux',
    'oracle-linux', 'amazon-linux',
  ] as LinuxDistro[],

  minimal: [
    'alpine-linux', 'void-linux', 'slackware', 'tiny-core', 'puppy-linux',
  ] as LinuxDistro[],

  security: [
    'kali-linux', 'parrot-os', 'blackarch', 'tails', 'qubes-os',
  ] as LinuxDistro[],

  bsd: [
    'freebsd', 'openbsd', 'netbsd', 'ghostbsd',
  ] as LinuxDistro[],
};
